### ISSUE TITLE
Final chapter 6 examples broken

### ISSUE THREAD

**Issue by ptdecker** [marcwan/LearningNodeJS#10]
Within content/album.js in chapter 6 (using the code from your github repository, not the out of date in the book code), you have:

    $.getJSON("/albums/" + album_name + ".json", function(d) {
        var photo_d = massage_album(d);
        $.extend(tdata, photo_d);
    }

This causes a 'unexpected identifier' error. I believe it is due to 'album_name' never being initialized anywhere.

Any hints on how to resolve this?

**Comment by marcwan** [comment]
Thanks for the updates. Yah, you want to be running server.js from templates/ to use the localhost:8080/page/home URL. Otherwise, for 05_server_static.js, it's just an example for testing out handling REST requests.
