### ISSUE TITLE
Error in Chapter 6, Page 131: incorrect URL

### ISSUE THREAD

**Issue by dakoo** [marcwan/LearningNodeJS#17]
Error in Chapter 6, Page 131, incorrect URL is used. 

I think you should replace
- http://localhost:8080/page/home 

with 

- http://localhost:8080/pages/home 

There are two lines. One is for web browsers, and another is for command line using curl.

**Comment by marcwan** [comment]
Nice, thanks! Updated the errata to reflect this.
