### ISSUE TITLE
the minutes in the date field for mysql example is 80

### ISSUE THREAD

**Issue by ConnectedReasoning** [marcwan/LearningNodeJS#19]
Chapter09/01_mysql_demos/01_mysql_testing.js contains a bad date in the pix data. (line 112) for filename="photo_03,jpg" the minues in the date field is 80.

**Comment by marcwan** [comment]
Well, that's bad. Let me take a look.

**Comment by marcwan** [comment]
OMG that's an amazing attention to detail, nice find!

Fixing.
