### ISSUE TITLE
issue in the example of chapter 6 

### ISSUE THREAD

**Issue by ciasom** [marcwan/LearningNodeJS#20]
To make the example in chapter 6 work (to show the images when clicking an album), handle_incoming_request has to have another else if branch, something like this:

```
else if(core_url.substr(0,8) == '/albums/' && core_url.substr(core_url.length-5) != '.json'){
    serve_static_file('albums/' + core_url.substr(8), res);
}
```

Otherwise the client can not request something like http://localhost:8080/albums/italy2012/xxx.jpg

**Comment by marcwan** [comment]
Thanks for the report! Do you want to submit a PR ?

**Comment by marcwan** [comment]
I'll take a look at this. Re-vamping all the code now.

**Comment by marcwan** [comment]
I've fixed all this for v2.
