### ISSUE TITLE
An issue in the book and sample codes of chapter 3

### ISSUE THREAD

**Issue by leoorpio** [marcwan/LearningNodeJS#22]
Hi,as I learned node.js .I found an issue in the book .In sample code Chapter03/09_expensive.js . the line "results[results.length] = arr1[ j ]" exist a problem.it should be arr2[ j ] .

**Comment by marcwan** [comment]
Hey, thanks so much for the bug report! Would you like to submit a PR? If so, I can merge it in. Otherwise, I can fix it too ^_^

**Comment by marcwan** [comment]
oh wait, this has already been fixed, check out the code in Chapter03/09_expensive.js

Thanks for the report!
