### ISSUE TITLE
bad_json() & do_rename() 

### ISSUE THREAD

**Issue by javajared** [marcwan/LearningNodeJS#27]
I am working through your Chapter 4 example => specially writing out the post_data.js file. I noticed that the bad_json() and do_rename() functions are both undefined. So I came here and found that a few years ago someone asked about the bad_json() function (https://github.com/marcwan/LearningNodeJS/issues/3). At that point in time you noted that the bad_json() method was defined at the bottom of the 08_post_data.js file. However, I do not see it defined currently, and I also do not see the do_rename() function either. Would you mind writing those into your 08_post_data.js file?

**Comment by marcwan** [comment]
Hi!

Thanks for the report. Let me take a look.

**Comment by marcwan** [comment]
Yes, I seem to have grabbed the wrong version of this file. Fixing.

**Comment by marcwan** [comment]
Fixed and checked in. Thanks again!

**Comment by javajared** [comment]
Thanks!!
