### ISSUE TITLE
Is ./ optional?

### ISSUE THREAD

**Issue by SecretTitle** [marcwan/LearningNodeJS#35]
I'm reading Learning NodeJS...  There are 2 distinct **fs.readdir** examples

Page 96:  The path includes ./
Page 73:  The path does not specify ./

Thank you in advance!

**Comment by marcwan** [comment]
Hi, thanks for the note!

./ is actually a bit safer, but if you're in the right directory already, not completely necessary. I try to be disciplined and safe about it, but sometimes, it's easy to just be lazy and skip it ^_^
