### ISSUE TITLE
Error in file examples (chapter 3)

### ISSUE THREAD

**Issue by maparrar** [marcwan/LearningNodeJS#5]
Hi Marc,

I don't know if it's an error or I don't get the idea.

In the example  07_this_self_error.js: (https://github.com/marcwan/LearningNodeJS/blob/master/Chapter03/07_this_self_error.js), in the line 20. The use of the callback function must be <code>callback(err,false);</code> or else the output will be:

 <code>About to open: file_that_does_not_exist
Can't open: file_that_does_not_exist
file exists!!!
</code>

Same in the 08_this_self_fixed.js example, line 22.

Best.

**Comment by marcwan** [comment]
thanks! (And sorry it's not very timely!)
