### ISSUE TITLE
Incorrect date on chapter09/01_mysql_demos/01_mysql_testing.js

### ISSUE THREAD

**Issue by ghost** [marcwan/LearningNodeJS#6]
Incorrect date causes MySQL error

>** 2b. create albums.
>undefined

>** 2c. create albums.
>undefined

>** 3. Add pictures.
>Aw, there was an error: 
>{ [Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2010/06/12 >08:80:40' for column 'date' at row 1]
>  code: 'ER_TRUNCATED_WRONG_VALUE',
>  errno: 1292,
>  sqlState: '22007',
>  index: 0 }

This error was caused by the following data.

            { filename: "photo_03.jpg",
              albumid: "japan2010",
              description: "shinjuku is nice",
              date: "2010/06/12 08:80:40" },

**Comment by marcwan** [comment]
Thanks! Fixed.
