### ISSUE TITLE
Chapter 1 Questions

### ISSUE THREAD

**Issue by arbrow06** [marcwan/LearningNodeJS#8]
I ran the debugging.js program and it still prints out 'Thanks for calling!' despite the error in the variable content_length. The value for that in the header is still undefined but the rest of the script works perfectly.

**Comment by marcwan** [comment]
This works properly in newer versions of node and hangs in the browser (because everything is grumpy).

Please let me know if you're still seeing this problem. I'd love to fix it if it still happens!
