### ISSUE TITLE
connect and express issue 

### ISSUE THREAD

**Issue by wonderdogone** [marcwan/LearningNodeJS#9]
In chapter 8 the example 02_create_album run but the DB is not updating on init. It should be showing a new a PhotoAlbums db but it does not. 
Getting this on launching  server.js

connect deprecated multipart: use parser (multiparty, busboy, formidable) direct
ly node_modules\express\node_modules\connect\lib\middleware\bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read node_modules
\express\node_modules\connect\lib\middleware\multipart.js:86:15

Even if I try and force express versions before 4 in which connect is not longer a dependency it still does the same. Not sure if it's express of mongoddb issue?

**Comment by marcwan** [comment]
I've updated all this for v2.
